### ISSUE TITLE
求GPT3的微调脚本或者docker环境

### ISSUE THREAD

**Issue by ZeyuTeng96** [anonNo2/crosstalk-generation#1]
大佬，您好：

看了您的例子，发现介绍的很全面，但是对于GPT3模型的微调脚本好像没有找到，能否请大佬提供一个GPT3的微调脚本或者docker环境。

谢谢大佬

**Comment by anonNo2** [comment]
您好，感谢关注

GPT3调用脚本什么的好说，下面举个栗子。
不放GPT3的相关调用是怕哪一次忽略把app-key提上去。
关键的是要有APP-KEY呀，这个是需要自己申请的，调用多的话需要花美刀。
传送门：[openai](https://beta.openai.com/)
示例如下：

```python

import openai
openai.api_key = 'xxxxxxx(需要自己申请的)'
def get_gpt3_turns_by_prompt(input_text,max_len=384):
    '''
    根据输入文本获取一个段落
    :param input_text: 输入文本
    :param max_len: 生成最大长度
    :return: 
    '''
    
    response = openai.Completion.create(
        # 使用官方引擎是engine，使用自己finetune的模型是model
        # engine="davinci",
        model='davinci:ft-unipd-2022-02-28-13-36-56',
        prompt=input_text,
        temperature=0.5,
        max_tokens=max_len,
        top_p=0.1,
        frequency_penalty=0.5,
        presence_penalty=0.5
    )

    text_ = response.last_response.data['choices'][0]['text']
    lines = text_.split('\n')
    return lines

def get_gpt3_sentence_by_prompt(input_text,max_len=64):
    '''
    根据输入文本获取一句
    :param input_text: 输入文本
    :param max_len: 生成最大长度
    :return: 
    '''
    
    response = openai.Completion.create(
        # 使用官方引擎是engine，使用自己finetune的模型是model
        # engine="davinci",
        model='davinci:ft-unipd-2022-02-28-13-36-56',
        prompt=input_text,
        temperature=0.5,
        max_tokens=max_len,
        top_p=0.1,
        frequency_penalty=0.5,
        presence_penalty=0.0,
        stop=['0:','1:','\n']
    )

    text_ = response.last_response.data['choices'][0]['text']
    return text_

```

**Comment by ZeyuTeng96** [comment]
> 您好，感谢关注
> 
> GPT3调用脚本什么的好说，下面举个栗子。 不放GPT3的相关调用是怕哪一次忽略把app-key提上去。 关键的是要有APP-KEY呀，这个是需要自己申请的，调用多的话需要花美刀。 传送门：[openai](https://beta.openai.com/) 示例如下：
> 
> ```python
> import openai
> openai.api_key = 'xxxxxxx(需要自己申请的)'
> def get_gpt3_turns_by_prompt(input_text,max_len=384):
>     '''
>     根据输入文本获取一个段落
>     :param input_text: 输入文本
>     :param max_len: 生成最大长度
>     :return: 
>     '''
>     
>     response = openai.Completion.create(
>         # 使用官方引擎是engine，使用自己finetune的模型是model
>         # engine="davinci",
>         model='davinci:ft-unipd-2022-02-28-13-36-56',
>         prompt=input_text,
>         temperature=0.5,
>         max_tokens=max_len,
>         top_p=0.1,
>         frequency_penalty=0.5,
>         presence_penalty=0.5
>     )
> 
>     text_ = response.last_response.data['choices'][0]['text']
>     lines = text_.split('\n')
>     return lines
> 
> def get_gpt3_sentence_by_prompt(input_text,max_len=64):
>     '''
>     根据输入文本获取一句
>     :param input_text: 输入文本
>     :param max_len: 生成最大长度
>     :return: 
>     '''
>     
>     response = openai.Completion.create(
>         # 使用官方引擎是engine，使用自己finetune的模型是model
>         # engine="davinci",
>         model='davinci:ft-unipd-2022-02-28-13-36-56',
>         prompt=input_text,
>         temperature=0.5,
>         max_tokens=max_len,
>         top_p=0.1,
>         frequency_penalty=0.5,
>         presence_penalty=0.0,
>         stop=['0:','1:','\n']
>     )
> 
>     text_ = response.last_response.data['choices'][0]['text']
>     return text_
> ```

请问大佬，那微调呢？是如何进行GPT3的微调的呢？

**Comment by anonNo2** [comment]
微调看你是要微调什么任务呀，openai上有一个目录专门是针对各个任务的gpt3微调指南，应该会比我描述的详细很多

**Comment by ZeyuTeng96** [comment]
> 微调看你是要微调什么任务呀，openai上有一个目录专门是针对各个任务的gpt3微调指南，应该会比我描述的详细很多

就是类似于您用gpt3微调了一个相声聊天对话人物一样，想用gpt3微调一个闲聊对话模型。大佬能否指个路

**Comment by anonNo2** [comment]
[gpt3_finetune_guide](https://github.com/anonNo2/crosstalk-generation/tree/main/src/beta_code/gpt3_finetune_guide)

目录之下刚上传了一个finetune时的随笔记录
还有一个10条数据的finetune数据demo
希望能帮到你

**Comment by ZeyuTeng96** [comment]
谢谢大佬，还能否请问下pangu-a的具体模型下载地址是哪个？在Hugging face上尝试过搜索不知道哪个是您测试中所使用的，我也想试试看效果

**Comment by anonNo2** [comment]
https://huggingface.co/imone/pangu_2_6B
我用的是这个，感觉0-shot效果是真的挺不尽人意的

**Comment by ZeyuTeng96** [comment]
大佬，最近在尝试用GPT2和GPT进行微调做类似于相声对话这种的闲聊任务，您这个开源项目做的也好，也很多人关注，能不能考虑再开源点代码、数据、镜像等？openai这种付费的确实不能开源，能否考虑开一些用GPT2训练相声对话的镜像这种？
